name: CI/CD for Flask GraphQL App

on:
  push:
    branches:
      - main
      - feature/tests  # Include feature branch

jobs:
  build:
    runs-on: ubuntu-latest
    services: 
      mysql:
        image: mysql:5.7
        
        ports: ['3306:3306']
        env:
          MYSQL_ROOT_PASSWORD: Elias928
          MYSQL_DATABASE: movie_db
          MYSQL_USER: root
          MYSQL_PASSWORD: Elias928
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r movie_api/requirements.txt  # Updated path to requirements.txt
      
      - name: Set FLASK_APP environment variable
        run: echo "FLASK_APP=movie_api.app" >> $GITHUB_ENV

     
      - name: Run migrations
        run: |
          flask db upgrade  # Ensure migrations are applied

      - name: Run tests
        run: python -m unittest discover
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r movie_api/requirements.txt  # Updated path to requirements.txt

      - name: Deploy application
        run: |
          # Deployment commands go here based on your deployment steps
