name: CI/CD for Flask GraphQL App

on:
  push:
    branches:
      - main
      - feature/tests 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r movie_api.requirements.txt

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql-version: '5.7'
          database: 'movie_db'
          username: 'root'
          password: 'Elias928'  

      - name: Run migrations
        run: |
          python -m flask db upgrade  # Ensure migrations are applied

      - name: Run tests
        run: python -m unittest discover

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.42'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r movie_api.requirements.txt

      - name: Deploy application
        run: |
          # Deployment commands go here
